from pathlib import Path
BASE_DIR = Path(__file__).parent
PROJECT_DIR = BASE_DIR.parent
VIDEOS_DIR = PROJECT_DIR / 'videos'
NORMAL_VIDEO = VIDEOS_DIR / '2.mp4'
TEST_VIDEO = VIDEOS_DIR / 'WhatsApp Video 2026-01-11 at 10.13.51 PM.mp4'
FRAMES_DIR = BASE_DIR / 'data' / 'frames'
EMBEDDINGS_DIR = BASE_DIR / 'data' / 'embeddings'
CHECKPOINTS_DIR = BASE_DIR / 'checkpoints'
CALIBRATION_FILE = CHECKPOINTS_DIR / 'calibration.json'
MAHAL_FILE = CHECKPOINTS_DIR / 'mahal_params.npz'
ENERGY_FILE = CHECKPOINTS_DIR / 'energy_model.pt'
TARGET_FPS = 3
FRAME_SIZE = 224
ENCODER_MODEL = 'vit_base_patch16_224'
EMBED_DIM = 768
NUM_PATCHES = 196
ENCODER_FREEZE_BLOCKS = 8
ENCODER_FINETUNE = True
ENCODER_LR = 1e-05
WINDOW_SIZE = 8
T_NUM_LAYERS = 4
T_NUM_HEADS = 8
T_HIDDEN_DIM = 768
T_FF_DIM = 2048
T_DROPOUT = 0.1
LONG_WINDOW_SIZE = 32
LONG_DOWNSAMPLE = 4
SPATIAL_NUM_HEADS = 8
SPATIAL_NUM_ENC_LAYERS = 3
SPATIAL_NUM_DEC_LAYERS = 2
MASK_RATIO = 0.5
EPOCHS = 30
BATCH_SIZE = 16
LEARNING_RATE = 0.0003
WEIGHT_DECAY = 0.0001
LOSS_ALPHA = 1.0
LOSS_BETA = 0.5
SVDD_DIM = 64
SVDD_NU = 0.1
SVDD_EPOCHS = 20
SVDD_LR = 0.0001
MC_DROPOUT_RATE = 0.1
MC_DROPOUT_PASSES = 20
SCORE_ALPHA = 0.3
SCORE_ALPHA_LONG = 0.1
SCORE_BETA = 0.25
SCORE_GAMMA = 0.15
SCORE_DELTA = 0.2
CALIBRATION_PERCENTILE = 97

# Lighting Robustness
USE_GRAYSCALE = False
GCN_ENABLE = True
AUGMENT_LIGHTING = True

import torch
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'